const data = [
  {
    id: 1,
    name: "Ram Kumar",
    dob: new Date("1990-01-01"),
    department: "IT",
    location: "Chennai",
    admin: false,
    email: "ram.kumar@example.com",
    password: "password123",
  },
  {
    id: 2,
    name: "Amit Sharma",
    dob: new Date("1985-05-15"),
    department: "Engineering",
    location: "Mumbai",
    admin: false,
    email: "amit.sharma@example.com",
    password: "password123",
  },
  {
    id: 3,
    name: "Priya Singh",
    dob: new Date("1992-08-22"),
    department: "Marketing",
    location: "Delhi",
    admin: false,
    email: "priya.singh@example.com",
    password: "password123",
  },
  {
    id: 4,
    name: "Ravi Kumar",
    dob: new Date("1988-11-30"),
    department: "Sales",
    location: "Bangalore",
    admin: false,
    email: "ravi.kumar@example.com",
    password: "password123",
  },
  {
    id: 5,
    name: "Anjali Patel",
    dob: new Date("1995-03-10"),
    department: "HR",
    location: "Chennai",
    admin: true,
    email: "anjali.patel@example.com",
    password: "password123",
  },
  {
    id: 6,
    name: "Vikram Desai",
    dob: new Date("1983-07-25"),
    department: "Finance",
    location: "Hyderabad",
    admin: false,
    email: "vikram.desai@example.com",
    password: "password123",
  }
];

export default data;